<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>moviewatch-local-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MovieWatch.Domain/MovieWatch.Domain.csproj" />
    <ProjectReference Include="../MovieWatch.Repository/MovieWatch.Repository.csproj" />
    <ProjectReference Include="../MovieWatch.Service/MovieWatch.Service.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
</Project>
